

<style>
    /* .model-inner-container .intro {margin-bottom:0;} */
    .colorpickerdisclaimer {font-size: 0.77rem;line-height: 1.5em;font-weight: 400;letter-spacing: 0.6px;margin: 20px 35px 20px 35px;max-width: unset; display: none;}
    .inner-color-container .color-name {text-align: center;}

    /* NEW SAI STYLE - 20200521 */
    .thestage {position:relative; background: none; transform: scale(1,1); margin: auto;}
    .canvascontainer {position: absolute; width: inherit; height: inherit;}
    .canvascontainer .canvasimg {position: absolute; display:none;}
    .acc-asset-holder {display: none;}

    .thecover {
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -o-user-select: none;
        user-select: none;
        background: rgba(0,0,0,0);
    }

    .model-indicator {max-width: 380px; position:absolute; bottom:0; padding:0 10px; left:50%; transform: translateX(-50%);}
    @media only screen and (max-width:900px){
        .colorpickerdisclaimer {margin: 20px 30% 20px 30%;}
    }
    @media only screen and (max-width:600px){
        .colorpickerdisclaimer {margin: 20px 15% 20px 15%;}
    }
    @media only screen and (max-width:540px){
        .model-indicator {width: 50%;}
    }
</style>

<script>
    var asset_url = '<?php echo env('AWS_CLOUDFRONT_URL'); ?>';
    var color_api = '{{url("/api/model_".$model_slug."_colors.json")}}';
    var accessories_api = '{{url("/api/model_".$model_slug."_accessories.json")}}';
</script>
<script src="{{versioned_asset('js/page/model_ext360.js')}}"></script>

    @if ($model_slug != 'city' && $model_slug != 'city-hatchback' && $model_slug!='civic' && $model_slug != 'hrv')
    <div class="inner-color-container">
        <div class="color-name sub-title ajax-cta-cname prime-title"></div>
        <div class="modelexterior">

            <img class="model-indicator" style="" src="{{url('img/mock/360indicator.png')}}" alt="" style="">

            <div class="exterior-holder thestage">

                <div class="thecar canvascontainer"></div>
                <div class="theacc canvascontainer"></div>
                <div class="thecover canvascontainer"></div>
            </div>
        </div>

        <div class="colortool">
            <div class="color-name sub-title ajax-cta-cname secondary-title"></div>
            <ul class="color-option-holder">
                {{--  GENERATED BY JS   --}}
            </ul>
            @php
                /*
                    SAI 20200507:
                    Accessories additional notes now set in DeltaEcho: model > Accessories > General Settings
                    No need to hard code aymore.
                    DO NOT hard code any content-related stuff unless in utter DESPERATION. Even then, update DeltaEcho to accomodate the content updates and remove the hardcode
                */

                if(@$model_info->accessories->additional_copy_title && @$model_info->accessories->additional_copy_content){
                    echo '<div class="colorpickerdisclaimer">';
                    echo '  <span style="font-weight:500;">'.$model_info->accessories->additional_copy_title.'</span>';
                    echo '  <br>'.$model_info->accessories->additional_copy_content;
                    echo '</div>';
                }
            @endphp


            <div class="colorpickerdisclaimer">
                {{--  Temporary will remove later   --}}

                @if(Request::is('model/jazz/exterior'))
                <span style="font-weight:500;">Honda Jazz is also available in:</span><br>Passion Red Pearl
                @endif
                @if(Request::is('model/civic/*'))
                <span style="font-weight:500;">Honda Civic is also available in:</span><br>Passion Red Pearl
                @endif
                @if(Request::is('model/hrv/*'))
                <span style="font-weight:500;">Honda HR-V is also available in:</span><br>Passion Red Pearl, Lunar Silver Metallic, Modern Steel Metallic
                @endif
            </div>
        </div>
        <div class="clearfix"></div>

    </div>
    @else
    <style>
        .model-inner-container .intro.first-ext-int{
            margin-top: 30px;
        }
    </style>
    @endif
